<a href="https://colab.research.google.com/github/priyatanwar018/Advance-Python/blob/main/AdvancePython02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**View vs Copy**

In [ ]:
import numpy as np

In [ ]:
a = np.array([10,20,30,40,50,60,70,80])   # View means modification in origianl data
b = a[2:5]
b[:] = 0
a

array([10, 20,  0,  0,  0, 60, 70, 80])

In [ ]:
a = np.array([10,20,30,40,50,60,70,80])   # Copy means modification in duplicate file
b = a[2:5].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

**Reshaping the Data**

In [ ]:
# We know that
# n(rows) * n(columns) = n(total_elements)
# if we have total_elements = 12
# 1*12, 12*1
# 2*6, 6*2
# 3*4, 4*3

# if we have total_elements 36
# 1*36, 36*1
# 2*18, 18*2
# 3*12, 12*3
# 4*9, 9*4
# 6*6

In [ ]:
a = np.random.randint(1,50,12)
a

array([21, 43,  1, 25, 15, 30, 12, 29, 35, 14, 34, 49])

In [ ]:
a.shape

(12,)

In [ ]:
a.reshape(2,6)

array([[21, 43,  1, 25, 15, 30],
       [12, 29, 35, 14, 34, 49]])

In [ ]:
a.reshape(6,2)

array([[21, 43],
       [ 1, 25],
       [15, 30],
       [12, 29],
       [35, 14],
       [34, 49]])

In [ ]:
a.reshape(3,4)

array([[21, 43,  1, 25],
       [15, 30, 12, 29],
       [35, 14, 34, 49]])

In [ ]:
b = np.random.randint(1,100,72)
b

array([77, 98, 92, 23, 86, 54, 39, 29, 85, 63, 39, 39, 20, 19, 10, 35, 47,
       87, 43, 12, 32, 53, 36, 15, 63, 26, 22, 60, 76, 56, 28, 45, 50, 99,
       39, 31, 76, 75, 34, 16,  6, 66, 30, 31, 79, 23, 86, 89, 61, 37,  9,
       51, 27, 71, 67, 19, 97, 48, 14,  4, 34, 37, 24, 44, 21, 28, 89, 58,
       71, 52, 94, 13])

In [ ]:
b.shape

(72,)

In [ ]:
# 1*72, 72*1
# 2*36, 36*2
# 3*24, 24*3
# 4*18, 18*4
# 6*12, 12*6
# 8*9, 9*8

In [ ]:
b.reshape(2,36)

array([[77, 98, 92, 23, 86, 54, 39, 29, 85, 63, 39, 39, 20, 19, 10, 35,
        47, 87, 43, 12, 32, 53, 36, 15, 63, 26, 22, 60, 76, 56, 28, 45,
        50, 99, 39, 31],
       [76, 75, 34, 16,  6, 66, 30, 31, 79, 23, 86, 89, 61, 37,  9, 51,
        27, 71, 67, 19, 97, 48, 14,  4, 34, 37, 24, 44, 21, 28, 89, 58,
        71, 52, 94, 13]])

In [ ]:
b.reshape(36,2)

array([[77, 98],
       [92, 23],
       [86, 54],
       [39, 29],
       [85, 63],
       [39, 39],
       [20, 19],
       [10, 35],
       [47, 87],
       [43, 12],
       [32, 53],
       [36, 15],
       [63, 26],
       [22, 60],
       [76, 56],
       [28, 45],
       [50, 99],
       [39, 31],
       [76, 75],
       [34, 16],
       [ 6, 66],
       [30, 31],
       [79, 23],
       [86, 89],
       [61, 37],
       [ 9, 51],
       [27, 71],
       [67, 19],
       [97, 48],
       [14,  4],
       [34, 37],
       [24, 44],
       [21, 28],
       [89, 58],
       [71, 52],
       [94, 13]])

In [ ]:
b.reshape(3,24)

array([[77, 98, 92, 23, 86, 54, 39, 29, 85, 63, 39, 39, 20, 19, 10, 35,
        47, 87, 43, 12, 32, 53, 36, 15],
       [63, 26, 22, 60, 76, 56, 28, 45, 50, 99, 39, 31, 76, 75, 34, 16,
         6, 66, 30, 31, 79, 23, 86, 89],
       [61, 37,  9, 51, 27, 71, 67, 19, 97, 48, 14,  4, 34, 37, 24, 44,
        21, 28, 89, 58, 71, 52, 94, 13]])

In [ ]:
b.reshape(24,3)

array([[77, 98, 92],
       [23, 86, 54],
       [39, 29, 85],
       [63, 39, 39],
       [20, 19, 10],
       [35, 47, 87],
       [43, 12, 32],
       [53, 36, 15],
       [63, 26, 22],
       [60, 76, 56],
       [28, 45, 50],
       [99, 39, 31],
       [76, 75, 34],
       [16,  6, 66],
       [30, 31, 79],
       [23, 86, 89],
       [61, 37,  9],
       [51, 27, 71],
       [67, 19, 97],
       [48, 14,  4],
       [34, 37, 24],
       [44, 21, 28],
       [89, 58, 71],
       [52, 94, 13]])

In [ ]:
b.reshape(4,18)

array([[77, 98, 92, 23, 86, 54, 39, 29, 85, 63, 39, 39, 20, 19, 10, 35,
        47, 87],
       [43, 12, 32, 53, 36, 15, 63, 26, 22, 60, 76, 56, 28, 45, 50, 99,
        39, 31],
       [76, 75, 34, 16,  6, 66, 30, 31, 79, 23, 86, 89, 61, 37,  9, 51,
        27, 71],
       [67, 19, 97, 48, 14,  4, 34, 37, 24, 44, 21, 28, 89, 58, 71, 52,
        94, 13]])

In [ ]:
b.reshape(18,4)

array([[77, 98, 92, 23],
       [86, 54, 39, 29],
       [85, 63, 39, 39],
       [20, 19, 10, 35],
       [47, 87, 43, 12],
       [32, 53, 36, 15],
       [63, 26, 22, 60],
       [76, 56, 28, 45],
       [50, 99, 39, 31],
       [76, 75, 34, 16],
       [ 6, 66, 30, 31],
       [79, 23, 86, 89],
       [61, 37,  9, 51],
       [27, 71, 67, 19],
       [97, 48, 14,  4],
       [34, 37, 24, 44],
       [21, 28, 89, 58],
       [71, 52, 94, 13]])

In [ ]:
b.reshape(6,12)

array([[77, 98, 92, 23, 86, 54, 39, 29, 85, 63, 39, 39],
       [20, 19, 10, 35, 47, 87, 43, 12, 32, 53, 36, 15],
       [63, 26, 22, 60, 76, 56, 28, 45, 50, 99, 39, 31],
       [76, 75, 34, 16,  6, 66, 30, 31, 79, 23, 86, 89],
       [61, 37,  9, 51, 27, 71, 67, 19, 97, 48, 14,  4],
       [34, 37, 24, 44, 21, 28, 89, 58, 71, 52, 94, 13]])

In [ ]:
b.reshape(12,6)

array([[77, 98, 92, 23, 86, 54],
       [39, 29, 85, 63, 39, 39],
       [20, 19, 10, 35, 47, 87],
       [43, 12, 32, 53, 36, 15],
       [63, 26, 22, 60, 76, 56],
       [28, 45, 50, 99, 39, 31],
       [76, 75, 34, 16,  6, 66],
       [30, 31, 79, 23, 86, 89],
       [61, 37,  9, 51, 27, 71],
       [67, 19, 97, 48, 14,  4],
       [34, 37, 24, 44, 21, 28],
       [89, 58, 71, 52, 94, 13]])

In [ ]:
b.reshape(8,9)

array([[77, 98, 92, 23, 86, 54, 39, 29, 85],
       [63, 39, 39, 20, 19, 10, 35, 47, 87],
       [43, 12, 32, 53, 36, 15, 63, 26, 22],
       [60, 76, 56, 28, 45, 50, 99, 39, 31],
       [76, 75, 34, 16,  6, 66, 30, 31, 79],
       [23, 86, 89, 61, 37,  9, 51, 27, 71],
       [67, 19, 97, 48, 14,  4, 34, 37, 24],
       [44, 21, 28, 89, 58, 71, 52, 94, 13]])

In [ ]:
b.reshape(9,8)

array([[77, 98, 92, 23, 86, 54, 39, 29],
       [85, 63, 39, 39, 20, 19, 10, 35],
       [47, 87, 43, 12, 32, 53, 36, 15],
       [63, 26, 22, 60, 76, 56, 28, 45],
       [50, 99, 39, 31, 76, 75, 34, 16],
       [ 6, 66, 30, 31, 79, 23, 86, 89],
       [61, 37,  9, 51, 27, 71, 67, 19],
       [97, 48, 14,  4, 34, 37, 24, 44],
       [21, 28, 89, 58, 71, 52, 94, 13]])

**Conditional Selection in NumPy**

In [ ]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
a < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [ ]:
b = a > 10
a[b]

array([11, 12, 13, 14, 15])

In [ ]:
c = a <= 10
a[c]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
a[a % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a + b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a - b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a * b  ## Wrong way

array([[ 5, 12],
       [21, 32]])

In [ ]:
a.dot(b)  ## Correct way

array([[19, 22],
       [43, 50]])

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(a)

45

In [ ]:
np.sum(a, axis = 1)  ## row wise total [in pandas axis = 1 means column wise total]

array([ 6, 15, 24])

In [ ]:
np.sum(a, axis = 0)  ## column wise total [in pandas axis = 0 means row wise total]

array([12, 15, 18])

In [ ]:
# Unique() ===> It wil return unique values or eliminate duplicate values
# It wil return 3 array
# (1) Unique value's array
# (2) Indexing of original value
# (3) Returns frequency of each unique value

In [ ]:
a = np.array([1,2,2,2,3,3,4,4,4,4,4,3,3,3,5,5,6])
a

array([1, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4, 3, 3, 3, 5, 5, 6])

In [ ]:
np.unique(a, return_index = True, return_counts = True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  4,  6, 14, 16]),
 array([1, 3, 5, 5, 2, 1]))

In [ ]:
# Linspace() ===> It will create an array in which difference of each value will be equal

In [ ]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Stacking in Numpy
# (1) hstack ===> It will combine arrays horizontally

In [ ]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

In [ ]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# (2) vstack ===> It will combine multiple arrays vertically

In [ ]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

In [ ]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])