# **NumPy Library**

In [ ]:
# Numpy ===> Numpy is an open source library that is used for scientific calculations

In [ ]:
# Why we use Numpy whenever we have list?
# (1) Homogeneous data type
# (2) Consume less memory
# (3) Consume less time

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = [1,34,67,90]
type(a)

list

In [ ]:
b = np.array(a)
b

array([ 1, 34, 67, 90])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
# Dimension
# 1-D ===> element exist in x-direction
# 2-D ===> element exist in x and y direction
# 3-D ===> element exist in x, y and z direction

In [ ]:
print("Total shape:" , b.shape) #shape = n(rows), n(columns)

Total shape: (4,)


In [ ]:
print("Total elements:", b.size) #size = n(rows)*n(columns)

Total elements: 4


In [ ]:
print("Total Dimension:", b.ndim) # ndim refers to dimension of array

Total Dimension: 1


In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:

type(a)

list

In [ ]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
print("Total rows and columns:", b.shape)
print("Total elements:", b.size)
print("Total dimension:", b.ndim)

Total rows and columns: (3, 3)
Total elements: 9
Total dimension: 2


# **How can we create a user defined array?**

In [ ]:
a = []
size = int(input("Enter the size of array: "))
for i in range(size):
  val = int(input("Enter number: "))
  a.append(val)
b = np.array(a)
b

Enter the size of array: 5
Enter number: 12
Enter number: 23
Enter number: 34
Enter number: 45
Enter number: 56


array([12, 23, 34, 45, 56])

**Numpy Functions**

In [ ]:
# Images ====> pixels
# (0-255)px ===> 0px(black), 255px(white)
# normalize ===> (0-1)px, 0(black), 1(white)
# 16 = 64
# 8 = 32
# 4 = 1

# (a) black & white image ===> height, width
# (b) colorful image ===> height, width, color_channel(red, green, blue)

# Matrix
# n(rows) = n(columns) ===> Symmetric matrix
# n(rows) != n(columns) ===> Non-symmetric matrix

# random number generation ===> random module

# Data Science ===> Simple line equation ===> y = mx + b   ## (x,y) = co-rodinates, m = slope/weight, b = intercept(constant)

# Matrix ==> rows and columns
# Matrix ==> diagonal position element = [(1,1),(2,2),(3,3)........(n,n)]

**(1) zeros() ===> it will create an array in which all the values are zero**

In [ ]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**(2) ones() ===> It will create an array in which all the values are 1**

In [ ]:
a = np.ones(3)
a

array([1., 1., 1.])

In [ ]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a.shape

(3, 4)

**(3) eye() ===> it will create an array in which diagonal position element are 1 and rest are 0 (2-D by default)**

In [ ]:
a = np.eye(3)  # symmetric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.eye(3,4) # non-symmetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

**(4) diag() ===> it will create an array in which we can customize our diagonal position elements**

In [ ]:
a = np.diag([1,56,89,700])
a

array([[  1,   0,   0,   0],
       [  0,  56,   0,   0],
       [  0,   0,  89,   0],
       [  0,   0,   0, 700]])

Random module

(a) OTP generation

(b) to generate random numbers

(c) dataset ===> add a dummy column

(d) initialize weights randomly in simple line equation

**(a) Randint(min_number, max_number, total_number)**

In [ ]:
a = np.random.randint(1,10,3)
a

array([7, 4, 5])

**(b) Rand(total_numbers) ===> it will return numbers from 0 to 1**

In [ ]:
a = np.random.rand(3)
a

array([0.10359608, 0.41420224, 0.8941162 ])

**(c) Randn() ===> -3 to +3**

In [ ]:
a = np.random.randn(3)
a

array([-0.7929334 ,  0.02569442, -2.03316631])

**(d) seed() ===> It will fix our data once the data has been generated**

In [ ]:
np.random.seed(20)
a = np.random.randint(1,10,3)
a

array([4, 5, 7])