<a href="https://colab.research.google.com/github/priyatanwar018/Advance-Python/blob/main/NumPy_DoOver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**December 11, 2024**

In [2]:
import numpy as np

In [ ]:
a = [1, 34, 67, 90]
type(a)

list

In [ ]:
b = np.array(a)
b

array([ 1, 34, 67, 90])

In [ ]:
type(b)

numpy.ndarray

**Shape, Size and Dimension**

In [ ]:
print("total shape: ",  b.shape)

total shape:  (4,)


In [ ]:
print("total elements: ", b.size)

total elements:  4


In [ ]:
print("Dimension: ", b.ndim)

Dimension:  1


In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print("Shape of b:", b.shape)

Shape of b: (3, 3)


In [ ]:
print("Total elements in b: ", b.size)

Total elements in b:  9


In [ ]:
print("Dimension of b: ", b.ndim)

Dimension of b:  2


**Creating a user defined array**

In [ ]:
a = []
size = int(input("Enter the size of array: "))
for i in range(size):
  val = int(input("Enter the value: "))
  a.append(val)
b = np.array(a)
b

Enter the size of array: 5
Enter the value: 12
Enter the value: 34
Enter the value: 56
Enter the value: 78
Enter the value: 89


array([12, 34, 56, 78, 89])

**NumPy Functions**

In [ ]:
# (1) zeros()
# (2) ones()
# (3) eye()
# (4) diag()
# (5) Random module

zeros()

In [ ]:
# all elements will be zero
a = np.zeros(3)   # One dimensional
a

array([0., 0., 0.])

In [ ]:
a = np.zeros((3,4))    # Two dimensional
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

ones()

In [ ]:
# all elements will be one
a = np.ones(3)
a

array([1., 1., 1.])

In [ ]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

eye()

In [ ]:
# diagonal elements will be 1 and rest will be 0
a = np.eye(3)    #Symmetric
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a.shape

(3, 3)

In [ ]:
a = np.eye(3,4)   # Asymmetric
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

diag()

In [ ]:
# we can customize our diagonal elements
a = np.diag([12,23,34,45])
a

array([[12,  0,  0,  0],
       [ 0, 23,  0,  0],
       [ 0,  0, 34,  0],
       [ 0,  0,  0, 45]])

random module

In [ ]:
a = np.random.randint(1,10,3)
a

array([6, 6, 4])

In [ ]:
a = np.random.rand(5)
a

array([0.04755122, 0.98956248, 0.03048111, 0.48241335, 0.63708032])

In [ ]:
a = np.random.randn(5)
a

array([-1.42292092, -0.71513774,  0.94009923,  2.06942684, -1.43740586])

In [ ]:
np.random.seed(25)
a = np.random.randint(1,10,3)
a

array([5, 7, 8])

**view vs copy**

In [ ]:
a = np.array([10,20,30,40,50,60,70,80,90])
b = a[2:5]
b[:] = 0
a

array([10, 20,  0,  0,  0, 60, 70, 80, 90])

In [ ]:
a = np.array([10,20,30,40,50,60,70,80,90])
b = a[2:5].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

**reshaping the data**

In [ ]:
a = np.random.randint(1,50,12)
a

array([45,  9, 29,  5, 26, 32,  6,  2, 40,  4, 25,  4])

In [ ]:
a.shape

(12,)

In [ ]:
a.reshape(2,6)

array([[45,  9, 29,  5, 26, 32],
       [ 6,  2, 40,  4, 25,  4]])

In [ ]:
a.reshape(6,2)

array([[45,  9],
       [29,  5],
       [26, 32],
       [ 6,  2],
       [40,  4],
       [25,  4]])

In [ ]:
a.reshape(3,4)

array([[45,  9, 29,  5],
       [26, 32,  6,  2],
       [40,  4, 25,  4]])

In [ ]:
a.reshape(4,3)

array([[45,  9, 29],
       [ 5, 26, 32],
       [ 6,  2, 40],
       [ 4, 25,  4]])

In [ ]:
b = np.random.randint(1,100,72)
b

array([85, 46,  4,  2, 23, 32, 49, 48, 74, 17, 51, 86, 37, 10, 33, 11, 61,
       48,  2, 87, 92, 50, 19, 93, 37, 99, 31, 39,  3,  6, 58, 74, 23, 12,
        3, 44, 91, 62, 85, 84, 75, 18, 15, 84, 38, 88, 51, 52, 15, 72, 63,
       91, 16, 15, 77, 40, 89, 47, 54, 30, 14, 47, 54, 63, 68,  3, 45, 45,
       64, 46, 25, 10])

In [ ]:
b.shape

(72,)

In [ ]:
b.reshape(2,36)

array([[85, 46,  4,  2, 23, 32, 49, 48, 74, 17, 51, 86, 37, 10, 33, 11,
        61, 48,  2, 87, 92, 50, 19, 93, 37, 99, 31, 39,  3,  6, 58, 74,
        23, 12,  3, 44],
       [91, 62, 85, 84, 75, 18, 15, 84, 38, 88, 51, 52, 15, 72, 63, 91,
        16, 15, 77, 40, 89, 47, 54, 30, 14, 47, 54, 63, 68,  3, 45, 45,
        64, 46, 25, 10]])

In [ ]:
b.reshape(36,2)

array([[85, 46],
       [ 4,  2],
       [23, 32],
       [49, 48],
       [74, 17],
       [51, 86],
       [37, 10],
       [33, 11],
       [61, 48],
       [ 2, 87],
       [92, 50],
       [19, 93],
       [37, 99],
       [31, 39],
       [ 3,  6],
       [58, 74],
       [23, 12],
       [ 3, 44],
       [91, 62],
       [85, 84],
       [75, 18],
       [15, 84],
       [38, 88],
       [51, 52],
       [15, 72],
       [63, 91],
       [16, 15],
       [77, 40],
       [89, 47],
       [54, 30],
       [14, 47],
       [54, 63],
       [68,  3],
       [45, 45],
       [64, 46],
       [25, 10]])

In [ ]:
b.reshape(3,24)

array([[85, 46,  4,  2, 23, 32, 49, 48, 74, 17, 51, 86, 37, 10, 33, 11,
        61, 48,  2, 87, 92, 50, 19, 93],
       [37, 99, 31, 39,  3,  6, 58, 74, 23, 12,  3, 44, 91, 62, 85, 84,
        75, 18, 15, 84, 38, 88, 51, 52],
       [15, 72, 63, 91, 16, 15, 77, 40, 89, 47, 54, 30, 14, 47, 54, 63,
        68,  3, 45, 45, 64, 46, 25, 10]])

In [ ]:
b.reshape(24,3)

array([[85, 46,  4],
       [ 2, 23, 32],
       [49, 48, 74],
       [17, 51, 86],
       [37, 10, 33],
       [11, 61, 48],
       [ 2, 87, 92],
       [50, 19, 93],
       [37, 99, 31],
       [39,  3,  6],
       [58, 74, 23],
       [12,  3, 44],
       [91, 62, 85],
       [84, 75, 18],
       [15, 84, 38],
       [88, 51, 52],
       [15, 72, 63],
       [91, 16, 15],
       [77, 40, 89],
       [47, 54, 30],
       [14, 47, 54],
       [63, 68,  3],
       [45, 45, 64],
       [46, 25, 10]])

In [ ]:
b.reshape(4,18)

array([[85, 46,  4,  2, 23, 32, 49, 48, 74, 17, 51, 86, 37, 10, 33, 11,
        61, 48],
       [ 2, 87, 92, 50, 19, 93, 37, 99, 31, 39,  3,  6, 58, 74, 23, 12,
         3, 44],
       [91, 62, 85, 84, 75, 18, 15, 84, 38, 88, 51, 52, 15, 72, 63, 91,
        16, 15],
       [77, 40, 89, 47, 54, 30, 14, 47, 54, 63, 68,  3, 45, 45, 64, 46,
        25, 10]])

In [ ]:
b.reshape(18,4)

array([[85, 46,  4,  2],
       [23, 32, 49, 48],
       [74, 17, 51, 86],
       [37, 10, 33, 11],
       [61, 48,  2, 87],
       [92, 50, 19, 93],
       [37, 99, 31, 39],
       [ 3,  6, 58, 74],
       [23, 12,  3, 44],
       [91, 62, 85, 84],
       [75, 18, 15, 84],
       [38, 88, 51, 52],
       [15, 72, 63, 91],
       [16, 15, 77, 40],
       [89, 47, 54, 30],
       [14, 47, 54, 63],
       [68,  3, 45, 45],
       [64, 46, 25, 10]])

In [ ]:
b.reshape(6,12)

array([[85, 46,  4,  2, 23, 32, 49, 48, 74, 17, 51, 86],
       [37, 10, 33, 11, 61, 48,  2, 87, 92, 50, 19, 93],
       [37, 99, 31, 39,  3,  6, 58, 74, 23, 12,  3, 44],
       [91, 62, 85, 84, 75, 18, 15, 84, 38, 88, 51, 52],
       [15, 72, 63, 91, 16, 15, 77, 40, 89, 47, 54, 30],
       [14, 47, 54, 63, 68,  3, 45, 45, 64, 46, 25, 10]])

In [ ]:
b.reshape(12,6)

array([[85, 46,  4,  2, 23, 32],
       [49, 48, 74, 17, 51, 86],
       [37, 10, 33, 11, 61, 48],
       [ 2, 87, 92, 50, 19, 93],
       [37, 99, 31, 39,  3,  6],
       [58, 74, 23, 12,  3, 44],
       [91, 62, 85, 84, 75, 18],
       [15, 84, 38, 88, 51, 52],
       [15, 72, 63, 91, 16, 15],
       [77, 40, 89, 47, 54, 30],
       [14, 47, 54, 63, 68,  3],
       [45, 45, 64, 46, 25, 10]])

In [ ]:
b.reshape(8,9)

array([[85, 46,  4,  2, 23, 32, 49, 48, 74],
       [17, 51, 86, 37, 10, 33, 11, 61, 48],
       [ 2, 87, 92, 50, 19, 93, 37, 99, 31],
       [39,  3,  6, 58, 74, 23, 12,  3, 44],
       [91, 62, 85, 84, 75, 18, 15, 84, 38],
       [88, 51, 52, 15, 72, 63, 91, 16, 15],
       [77, 40, 89, 47, 54, 30, 14, 47, 54],
       [63, 68,  3, 45, 45, 64, 46, 25, 10]])

In [ ]:
b.reshape(9,8)

array([[85, 46,  4,  2, 23, 32, 49, 48],
       [74, 17, 51, 86, 37, 10, 33, 11],
       [61, 48,  2, 87, 92, 50, 19, 93],
       [37, 99, 31, 39,  3,  6, 58, 74],
       [23, 12,  3, 44, 91, 62, 85, 84],
       [75, 18, 15, 84, 38, 88, 51, 52],
       [15, 72, 63, 91, 16, 15, 77, 40],
       [89, 47, 54, 30, 14, 47, 54, 63],
       [68,  3, 45, 45, 64, 46, 25, 10]])

**Conditional selection in numpy**

In [3]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [5]:
a < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [6]:
b = a > 10
a[b]

array([11, 12, 13, 14, 15])

In [7]:
c = a < 10
a[c]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [9]:
a[a % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [10]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [11]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [12]:
a + b

array([[ 6,  8],
       [10, 12]])

In [13]:
a - b

array([[-4, -4],
       [-4, -4]])

In [14]:
a * b  # wrong way

array([[ 5, 12],
       [21, 32]])

In [15]:
a.dot(b) # right way

array([[19, 22],
       [43, 50]])

In [16]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.sum(a)

45

In [18]:
np.sum(a, axis = 1) # row wise total

array([ 6, 15, 24])

In [19]:
np.sum(a, axis = 0) # column wise total

array([12, 15, 18])

In [20]:
# Unique() ===> It will return unique values or eliminate duplicate values
# It will return 3 array
# (1) Unique value's array
# (2) Indexing of original value
# (3) Returns frequency of each unique value

In [21]:
a = np.array([1,1,1,2,2,2,23,3,3,3,3,2,24,4,3,35,5,5,4])
a

array([ 1,  1,  1,  2,  2,  2, 23,  3,  3,  3,  3,  2, 24,  4,  3, 35,  5,
        5,  4])

In [22]:
np.unique(a, return_index = True, return_counts = True)

(array([ 1,  2,  3,  4,  5, 23, 24, 35]),
 array([ 0,  3,  7, 13, 16,  6, 12, 15]),
 array([3, 4, 5, 2, 2, 1, 1, 1]))

In [23]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

In [25]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

In [27]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])